<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class FreelanceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $freelances = [
            [
                'nama' => 'Ahmad Freelance',
                'email' => 'ahmad.freelance@gmail.com',
                'no_wa' => '081234567891',
                'provinsi' => 'DKI Jakarta',
                'kab_kota' => 'Jakarta Selatan',
                'alamat_lengkap' => 'Jl. Sudirman No. 45, Jakarta Selatan, DKI Jakarta 12190',
                'date_register' => Carbon::now()->subDays(30)->format('Y-m-d'),
                'is_active' => true,
                'link_referral' => 'ahmad-freelance',
                'ref_code' => 'FRL-AHMAD',
                'created_at' => Carbon::now()->subDays(30),
                'updated_at' => Carbon::now()->subDays(30),
            ],
            [
                'nama' => 'apip ',
                'email' => 'apiiipbackup@gmail.com',
                'no_wa' => '081234567892',
                'provinsi' => 'Jawa Timur',
                'kab_kota' => 'Surabaya',
                'alamat_lengkap' => 'Jl. Pahlawan No. 78, Surabaya, Jawa Timur 60175',
                'date_register' => Carbon::now()->subDays(25)->format('Y-m-d'),
                'is_active' => true,
                'link_referral' => 'apip-reelance',
                'ref_code' => 'FRL-APIPBACKUP',
                'created_at' => Carbon::now()->subDays(25),
                'updated_at' => Carbon::now()->subDays(25),
            ],
            [
                'nama' => 'Budi Santoso',
                'email' => 'budi.freelance@gmail.com',
                'no_wa' => '081234567893',
                'provinsi' => 'Jawa Tengah',
                'kab_kota' => 'Semarang',
                'alamat_lengkap' => 'Jl. Pemuda No. 12, Semarang, Jawa Tengah 50132',
                'date_register' => Carbon::now()->subDays(20)->format('Y-m-d'),
                'is_active' => true,
                'link_referral' => 'budi-freelance',
                'ref_code' => 'FRL-BUDI',
                'created_at' => Carbon::now()->subDays(20),
                'updated_at' => Carbon::now()->subDays(20),
            ],
            [
                'nama' => 'Dewi Lestari',
                'email' => 'dewi.freelance@gmail.com',
                'no_wa' => '081234567894',
                'provinsi' => 'Bali',
                'kab_kota' => 'Denpasar',
                'alamat_lengkap' => 'Jl. Sunset Road No. 99, Denpasar, Bali 80361',
                'date_register' => Carbon::now()->subDays(15)->format('Y-m-d'),
                'is_active' => true,
                'link_referral' => 'dewi-freelance',
                'ref_code' => 'FRL-DEWI',
                'created_at' => Carbon::now()->subDays(15),
                'updated_at' => Carbon::now()->subDays(15),
            ],
            [
                'nama' => 'Eko Prasetyo',
                'email' => 'eko.freelance@gmail.com',
                'no_wa' => '081234567895',
                'provinsi' => 'Yogyakarta',
                'kab_kota' => 'Yogyakarta',
                'alamat_lengkap' => 'Jl. Malioboro No. 56, Yogyakarta 55271',
                'date_register' => Carbon::now()->subDays(10)->format('Y-m-d'),
                'is_active' => true,
                'link_referral' => 'eko-freelance',
                'ref_code' => 'FRL-EKO',
                'created_at' => Carbon::now()->subDays(10),
                'updated_at' => Carbon::now()->subDays(10),
            ],
            [
                'nama' => 'Fitri Handayani',
                'email' => 'fitri.freelance@gmail.com',
                'no_wa' => '081234567896',
                'provinsi' => 'Sumatera Utara',
                'kab_kota' => 'Medan',
                'alamat_lengkap' => 'Jl. Asia No. 21, Medan, Sumatera Utara 20112',
                'date_register' => Carbon::now()->subDays(8)->format('Y-m-d'),
                'is_active' => true,
                'link_referral' => 'fitri-freelance',
                'ref_code' => 'FRL-FITRI',
                'created_at' => Carbon::now()->subDays(8),
                'updated_at' => Carbon::now()->subDays(8),
            ],
            [
                'nama' => 'Guntur Wijaya',
                'email' => 'guntur.freelance@gmail.com',
                'no_wa' => '081234567897',
                'provinsi' => 'Kalimantan Timur',
                'kab_kota' => 'Balikpapan',
                'alamat_lengkap' => 'Jl. Jenderal Sudirman No. 88, Balikpapan, Kalimantan Timur 76114',
                'date_register' => Carbon::now()->subDays(5)->format('Y-m-d'),
                'is_active' => true,
                'link_referral' => 'guntur-freelance',
                'ref_code' => 'FRL-GUNTUR',
                'created_at' => Carbon::now()->subDays(5),
                'updated_at' => Carbon::now()->subDays(5),
            ],
            [
                'nama' => 'Hana Permata',
                'email' => 'hana.freelance@gmail.com',
                'no_wa' => '081234567898',
                'provinsi' => 'Sulawesi Selatan',
                'kab_kota' => 'Makassar',
                'alamat_lengkap' => 'Jl. Veteran No. 34, Makassar, Sulawesi Selatan 90233',
                'date_register' => Carbon::now()->subDays(3)->format('Y-m-d'),
                'is_active' => true,
                'link_referral' => 'hana-freelance',
                'ref_code' => 'FRL-HANA',
                'created_at' => Carbon::now()->subDays(3),
                'updated_at' => Carbon::now()->subDays(3),
            ],
            [
                'nama' => 'Irfan Hakim',
                'email' => 'irfan.freelance@gmail.com',
                'no_wa' => '081234567899',
                'provinsi' => 'Lampung',
                'kab_kota' => 'Bandar Lampung',
                'alamat_lengkap' => 'Jl. Raden Intan No. 67, Bandar Lampung, Lampung 35214',
                'date_register' => Carbon::now()->subDays(2)->format('Y-m-d'),
                'is_active' => false,
                'link_referral' => 'irfan-freelance',
                'ref_code' => 'FRL-IRFAN',
                'created_at' => Carbon::now()->subDays(2),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            [
                'nama' => 'Joko Susanto',
                'email' => 'joko.freelance@gmail.com',
                'no_wa' => '081234567800',
                'provinsi' => 'Riau',
                'kab_kota' => 'Pekanbaru',
                'alamat_lengkap' => 'Jl. Sudirman No. 101, Pekanbaru, Riau 28155',
                'date_register' => Carbon::now()->subDays(1)->format('Y-m-d'),
                'is_active' => true,
                'link_referral' => 'joko-freelance',
                'ref_code' => 'FRL-JOKO',
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'nama' => 'Faiz Daffa',
                'email' => 'faizdaffanaut@gmail.com',
                'no_wa' => '0812345222800',
                'provinsi' => 'Jawa Timur',
                'kab_kota' => 'Surabaya',
                'alamat_lengkap' => 'Jl. Sudirman No. 101, Pekanbaru, Riau 28155',
                'date_register' => Carbon::now()->subDays(1)->format('Y-m-d'),
                'is_active' => true,
                'link_referral' => 'faizdaffanaut',
                'ref_code' => 'FRL-FAIZ',
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
        ];

        DB::table('freelances')->insert($freelances);
    }
}
