<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $produk = [
            [
                'id' => 'PRD-TSEL-001',
                'nama_paket' => 'Umroh Basic 15GB',
                'tipe_paket' => 'Internet',
                'provider' => 'TELKOMSEL',
                'masa_aktif' => 30,
                'total_kuota' => '15 GB',
                'kuota_utama' => '12 GB',
                'kuota_bonus' => '3 GB',
                'telp' => '100',
                'sms' => '50',
                'harga_modal' => 200000,
                'harga_app' => 0,
                'persentase_marginstar' => 0,
                'marginstar' => 0,
                'poin' => 0,
                'source_name' => 'MANUAL',
                'promo' => null,
            ],
            [
                'id' => 'PRD-ISAT-001',
                'nama_paket' => 'Premium 30GB',
                'tipe_paket' => 'Internet+Voice',
                'provider' => 'INDOSAT',
                'masa_aktif' => 30,
                'total_kuota' => '30 GB',
                'kuota_utama' => '25 GB',
                'kuota_bonus' => '5 GB',
                'telp' => '200',
                'sms' => '100',
                'harga_modal' => 350000,
                'harga_app' => 0,
                'persentase_marginstar' => 0,
                'marginstar' => 0,
                'poin' => 0,
                'source_name' => 'MANUAL',
                'promo' => null,
            ],
            [
                'id' => 'PRD-TSEL-002',
                'nama_paket' => 'Haji Ekonomis 10GB',
                'tipe_paket' => 'Internet',
                'provider' => 'TELKOMSEL',
                'masa_aktif' => 45,
                'total_kuota' => '10 GB',
                'kuota_utama' => '8 GB',
                'kuota_bonus' => '2 GB',
                'telp' => '80',
                'sms' => '40',
                'harga_modal' => 180000,
                'harga_app' => 0,
                'persentase_marginstar' => 0,
                'marginstar' => 0,
                'poin' => 0,
                'source_name' => 'MANUAL',
                'promo' => null,
            ],
            [
                'id' => 'PRD-XL-001',
                'nama_paket' => 'Super 50GB',
                'tipe_paket' => 'Internet+Voice',
                'provider' => 'XL',
                'masa_aktif' => 30,
                'total_kuota' => '50 GB',
                'kuota_utama' => '40 GB',
                'kuota_bonus' => '10 GB',
                'telp' => '300',
                'sms' => '150',
                'harga_modal' => 500000,
                'harga_app' => 0,
                'persentase_marginstar' => 0,
                'marginstar' => 0,
                'poin' => 0,
                'source_name' => 'MANUAL',
                'promo' => null,
            ],
            [
                'id' => 'PRD-ISAT-002',
                'nama_paket' => 'Unlimited',
                'tipe_paket' => 'Unlimited',
                'provider' => 'INDOSAT',
                'masa_aktif' => 30,
                'total_kuota' => 'Unlimited',
                'kuota_utama' => 'Unlimited',
                'kuota_bonus' => '0 GB',
                'telp' => '500',
                'sms' => '200',
                'harga_modal' => 600000,
                'harga_app' => 0,
                'persentase_marginstar' => 0,
                'marginstar' => 0,
                'poin' => 0,
                'source_name' => 'MANUAL',
                'promo' => null,
            ],
            [
                'id' => 'PRD-TRI-001',
                'nama_paket' => 'Express 20GB',
                'tipe_paket' => 'Internet',
                'provider' => 'TRI',
                'masa_aktif' => 15,
                'total_kuota' => '20 GB',
                'kuota_utama' => '18 GB',
                'kuota_bonus' => '2 GB',
                'telp' => '120',
                'sms' => '60',
                'harga_modal' => 250000,
                'harga_app' => 0,
                'persentase_marginstar' => 0,
                'marginstar' => 0,
                'poin' => 0,
                'source_name' => 'MANUAL',
                'promo' => null,
            ],
            [
                'id' => 'PRD-XL-002',
                'nama_paket' => 'Premium Plus 40GB',
                'tipe_paket' => 'Internet+Voice',
                'provider' => 'XL',
                'masa_aktif' => 30,
                'total_kuota' => '40 GB',
                'kuota_utama' => '35 GB',
                'kuota_bonus' => '5 GB',
                'telp' => '250',
                'sms' => '120',
                'harga_modal' => 420000,
                'harga_app' => 0,
                'persentase_marginstar' => 0,
                'marginstar' => 0,
                'poin' => 0,
                'source_name' => 'MANUAL',
                'promo' => null,
            ],
            [
                'id' => 'PRD-TSEL-003',
                'nama_paket' => 'Budget 8GB',
                'tipe_paket' => 'Internet',
                'provider' => 'TELKOMSEL',
                'masa_aktif' => 30,
                'total_kuota' => '8 GB',
                'kuota_utama' => '6 GB',
                'kuota_bonus' => '2 GB',
                'telp' => '60',
                'sms' => '30',
                'harga_modal' => 90000,
                'harga_app' => 0,
                'persentase_marginstar' => 0,
                'marginstar' => 0,
                'poin' => 0,
                'source_name' => 'MANUAL',
                'promo' => null,
            ],
        ];

        DB::table('produk')->insert($produk);
    }
}
