<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $produk = [
            [
                'nama_paket' => 'Umroh Basic 15GB',
                'tipe_paket' => 'Internet',
                'masa_aktif' => 30,
                'total_kuota' => 15000,
                'kuota_utama' => 12000,
                'kuota_bonus' => 3000,
                'telp' => 100,
                'sms' => 50,
                'harga_modal' => 200000,
                'harga_eup' => 250000,
                'persentase_margin_star' => 15.00,
                'margin_star' => 37500,
                'margin_total' => 50000,
                'fee_travel' => 20000,
                'persentase_fee_travel' => 8.00,
                'persentase_fee_affiliate' => 5.00,
                'fee_affiliate' => 12500,
                'persentase_fee_host' => 3.00,
                'fee_host' => 7500,
                'harga_tp_travel' => 230000,
                'harga_tp_host' => 242500,
                'poin' => 25,
                'profit' => 10000,
            ],
            [
                'nama_paket' => 'Premium 30GB',
                'tipe_paket' => 'Internet+Voice',
                'masa_aktif' => 30,
                'total_kuota' => 30000,
                'kuota_utama' => 25000,
                'kuota_bonus' => 5000,
                'telp' => 200,
                'sms' => 100,
                'harga_modal' => 350000,
                'harga_eup' => 450000,
                'persentase_margin_star' => 18.00,
                'margin_star' => 81000,
                'margin_total' => 100000,
                'fee_travel' => 35000,
                'persentase_fee_travel' => 7.78,
                'persentase_fee_affiliate' => 6.00,
                'fee_affiliate' => 27000,
                'persentase_fee_host' => 4.00,
                'fee_host' => 18000,
                'harga_tp_travel' => 385000,
                'harga_tp_host' => 423000,
                'poin' => 45,
                'profit' => 20000,
            ],
            [
                'nama_paket' => 'Haji Ekonomis 10GB',
                'tipe_paket' => 'Internet',
                'masa_aktif' => 45,
                'total_kuota' => 10000,
                'kuota_utama' => 8000,
                'kuota_bonus' => 2000,
                'telp' => 80,
                'sms' => 40,
                'harga_modal' => 180000,
                'harga_eup' => 220000,
                'persentase_margin_star' => 14.00,
                'margin_star' => 30800,
                'margin_total' => 40000,
                'fee_travel' => 15000,
                'persentase_fee_travel' => 6.82,
                'persentase_fee_affiliate' => 4.50,
                'fee_affiliate' => 9900,
                'persentase_fee_host' => 2.50,
                'fee_host' => 5500,
                'harga_tp_travel' => 195000,
                'harga_tp_host' => 210400,
                'poin' => 20,
                'profit' => 9200,
            ],
            [
                'nama_paket' => 'Super 50GB',
                'tipe_paket' => 'Internet+Voice',
                'masa_aktif' => 30,
                'total_kuota' => 50000,
                'kuota_utama' => 40000,
                'kuota_bonus' => 10000,
                'telp' => 300,
                'sms' => 150,
                'harga_modal' => 500000,
                'harga_eup' => 650000,
                'persentase_margin_star' => 20.00,
                'margin_star' => 130000,
                'margin_total' => 150000,
                'fee_travel' => 50000,
                'persentase_fee_travel' => 7.69,
                'persentase_fee_affiliate' => 7.00,
                'fee_affiliate' => 45500,
                'persentase_fee_host' => 5.00,
                'fee_host' => 32500,
                'harga_tp_travel' => 550000,
                'harga_tp_host' => 617500,
                'poin' => 65,
                'profit' => 22000,
            ],
            [
                'nama_paket' => 'Unlimited',
                'tipe_paket' => 'Unlimited',
                'masa_aktif' => 30,
                'total_kuota' => 999999,
                'kuota_utama' => 999999,
                'kuota_bonus' => 0,
                'telp' => 500,
                'sms' => 200,
                'harga_modal' => 600000,
                'harga_eup' => 800000,
                'persentase_margin_star' => 22.00,
                'margin_star' => 176000,
                'margin_total' => 200000,
                'fee_travel' => 60000,
                'persentase_fee_travel' => 7.50,
                'persentase_fee_affiliate' => 8.00,
                'fee_affiliate' => 64000,
                'persentase_fee_host' => 6.00,
                'fee_host' => 48000,
                'harga_tp_travel' => 660000,
                'harga_tp_host' => 736000,
                'poin' => 80,
                'profit' => 28000,
            ],
            [
                'nama_paket' => 'Express 20GB',
                'tipe_paket' => 'Internet',
                'masa_aktif' => 15,
                'total_kuota' => 20000,
                'kuota_utama' => 18000,
                'kuota_bonus' => 2000,
                'telp' => 120,
                'sms' => 60,
                'harga_modal' => 250000,
                'harga_eup' => 320000,
                'persentase_margin_star' => 16.00,
                'margin_star' => 51200,
                'margin_total' => 70000,
                'fee_travel' => 25000,
                'persentase_fee_travel' => 7.81,
                'persentase_fee_affiliate' => 5.50,
                'fee_affiliate' => 17600,
                'persentase_fee_host' => 3.50,
                'fee_host' => 11200,
                'harga_tp_travel' => 275000,
                'harga_tp_host' => 301200,
                'poin' => 32,
                'profit' => 15800,
            ],
            [
                'nama_paket' => 'Premium Plus 40GB',
                'tipe_paket' => 'Internet+Voice',
                'masa_aktif' => 30,
                'total_kuota' => 40000,
                'kuota_utama' => 35000,
                'kuota_bonus' => 5000,
                'telp' => 250,
                'sms' => 120,
                'harga_modal' => 420000,
                'harga_eup' => 550000,
                'persentase_margin_star' => 19.00,
                'margin_star' => 104500,
                'margin_total' => 130000,
                'fee_travel' => 42000,
                'persentase_fee_travel' => 7.64,
                'persentase_fee_affiliate' => 6.50,
                'fee_affiliate' => 35750,
                'persentase_fee_host' => 4.50,
                'fee_host' => 24750,
                'harga_tp_travel' => 462000,
                'harga_tp_host' => 524250,
                'poin' => 55,
                'profit' => 25500,
            ],
            [
                'nama_paket' => 'Budget 8GB',
                'tipe_paket' => 'Internet',
                'masa_aktif' => 30,
                'total_kuota' => 8000,
                'kuota_utama' => 6000,
                'kuota_bonus' => 2000,
                'telp' => 60,
                'sms' => 30,
                'harga_modal' => 90000,
                'harga_eup' => 120000,
                'persentase_margin_star' => 12.00,
                'margin_star' => 14400,
                'margin_total' => 30000,
                'fee_travel' => 10000,
                'persentase_fee_travel' => 8.33,
                'persentase_fee_affiliate' => 4.00,
                'fee_affiliate' => 4800,
                'persentase_fee_host' => 2.00,
                'fee_host' => 2400,
                'harga_tp_travel' => 100000,
                'harga_tp_host' => 114400,
                'poin' => 12,
                'profit' => 12800,
            ],
        ];

        DB::table('produk')->insert($produk);
    }
}
